#!/usr/bin/env ruby
lib = File.expand_path('../../.lib/lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'lldeclare/rbenv'

rbenv = LLDeclare::Rbenv.new
rbenv.exec("bundle exec " + ARGV.join(" "))
