#!/usr/bin/env ruby
lib = File.expand_path('../../.lib/lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'lldeclare/nvm'

version = File.expand_path('..', __FILE__).split("/").last.gsub(/^node-/, "") # using parent directory name
version = "v" + version
nvm = LLDeclare::Nvm.new
nvm.exec(version, ARGV.join(" "))
